const GeoLayout chain_chomp_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 199),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 13107),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chain_chomp_000_offset_001_mesh_layer_5),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_001_offset_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_000_offset_002_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chain_chomp_000_offset_002_mesh_layer_5),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_001_offset_001_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_002_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chain_chomp_002_offset_001_mesh_layer_5),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, chain_chomp_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chain_chomp_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
